# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bu-_nEndWA9o7zb98emFw529HmYJ9ewL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

#reading csv file
df = pd.read_csv("Iris.csv")
#printing first five rows
df.head()

#printing last five rows
df.tail()

df.shape

#printing all the information of dataset
df.info()

#checking for null values
df.isnull().sum()

df.describe()

df.columns

#drop unwanted columns
df = df.drop(columns="Id")

df.dtypes

df.nunique()

plt.figure(figsize=(10,10))
sns.heatmap(data=df.corr(), annot=True, cmap='Greens')

sns.pairplot(df, size=3)

#plot a boxplot
plt.figure(figsize=(30,30))
df.boxplot()

df['Species'].value_counts()

sns.countplot(df['Species'])

x = df.iloc[:,:4]
y = df.iloc[:,4]

x

y

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4,random_state=0)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

confusion_matrix(y_test,y_pred)

accuracy=accuracy_score(y_test,y_pred)*100
print("Accuracy of the model is {:.2f}".format(accuracy))